import express from 'express';
import { productController } from './product.controller';
import uploader from '../../../util/uploader';
const router = express.Router();
router.post('/create-product', uploader.single("productImage"), productController.createProduct);
router.post('/upload', uploader.single("image"), productController.uploadImages);
router.get('/get-product/:id', productController.getSingleProduct);
// router.patch('/update-product/:id', productController.updateProduct);
// router.delete('/delete-product/:id', productController.deleteProduct);
router.get('/get-products', productController.getAllProduct);
export const ProductRoutes = router;